version: "3.9"

services:
  web:
    image: registry.gitlab.com/konfuzio/text-annotation/master:latest
    volumes:
      - type: bind
        source: /konfuzio-vm/text-annotation/data
        target: /data
    ports:
      - "80:8000"
    # get env info from file
    env_file:
      - konfuzio_config.env

  worker:
    image: registry.gitlab.com/konfuzio/text-annotation/master:latest
    volumes:
      - type: bind
        source: /konfuzio-vm/text-annotation/data
        target: /data
    # start and configure celery
    command: celery -A app worker -l INFO --concurrency 1 -Q celery,extract,processing,local_ocr,ocr,training,training_heavy,finalize,categorize
    # get env info from file
    env_file:
      - konfuzio_config.env
    depends_on:
      - web
    deploy:
      mode: replicated
      # deploy 4 workers
      replicas: 4
      # restart when failing
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
